spring:
  profiles:
    active: local
    group:
      local: common
      blue: blue, common
      green: green, common

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: common

serverName: common


---

spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080


serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081


serverName: green_server

---