spring:
  profiles:
    active: local
    group:
      local: common, db2
      blue: blue, common, db
      green: green, common , db

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: common

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

serverName: common

---

spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080


serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081


serverName: green_server

---
